name: "SQLCheck Action"
description: "Automatically identify anti-patterns in SQL queries using SQLCheck"
author: "yokawasa"
inputs:
  post-comment:
    description: "Post comment to PR"
    default: true
    required: false
  token:
    description: "Github Token in order to add comment to PR"
    default: ""
    required: true
  risk-level:
    description: "Set of SQL anti-patterns to check: 1,2, or 3"
    default: "3"
    required: false
  verbose:
    description: "Add verbose warnings to SQLCheck analysis result"
    default: false
    required: false
  postfixes:
    description: "List of file postfix to match. Supported separators are comma (deprecating) and retrun in multi-line string"
    default: "sql"
    required: false
  directories:
    description: "Path(s) of directory under which the action check any files whether they are part of the repository or not. By default, the action checks only files in PR queries. By specifying directories the action no longer check files in PR queries but files under the directories (maxdepth 3). Supported separator is return in multi-line string"
    default: ""
    required: false
outputs:
  issue-found:
    description: 'A boolean value to indicate an issue was found in the files that sqlcheck action checked'
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.post-comment }}
    - ${{ inputs.token }}
    - ${{ inputs.risk-level }}
    - ${{ inputs.verbose }}
    - ${{ inputs.postfixes }}
    - ${{ inputs.directories }}
branding:
  icon: 'check-circle'
  color: 'black'
